### ISSUE TITLE
Speed increase depending on CPU temperature

### ISSUE THREAD

**Issue by werner69rock** [pingud98/rockpro64fanctrl#1]
Thank you for this simple solution to slow down the fan after boot.

I'm not familiar with Linux or any kind of programming, would it be possible to change the value of the fancontrol.sh when the CPU temperature changes?

For example:
Fan 0 until the temperature rises above 40°C
Fan 180 at temperature above 40°C
Fan 0 when temperature drops below 36°C

Regards Werner

**Comment by pingud98** [comment]
Hi Werner,

Short answer is yes, it's possible. Longer answer in terms of how to do it,
I don't really know myself! You would need a bash script that runs as a
daemon, or a little bit of python. My use case (NAS) has a flat load
profile, so I haven't ventured down this road! I'm sure you will find a
selection of good answers if you look hard enough.

Best regards,
James

**Comment by werner69rock** [comment]
Hi James,

more than a year later, but it's done.
Thanks again for your work, now I am super happy with this simple solution.

Best regards
Werner
[fancontrol.sh.txt](https://github.com/pingud98/rockpro64fanctrl/files/12795487/fancontrol.sh.txt)
